<? $this->placeholder('body_start')->captureStart(); ?>
            <? if(Zend_Auth::getInstance()->getIdentity()->getRole()->getRoleId() > 0): ?>
                Signed in as <?= Zend_Auth::getInstance()->getIdentity()->getUsername(); ?> | <a href="<?=$this->url(array('module'=>'auth', 'controller'=>'index','action'=>'logout'));?>">Sign Out</a>
            <? else: ?>
                <a href="<?=$this->url(array('module'=>'auth', 'controller'=>'index','action'=>'login'));?>">Sign In</a> |
                <a href="<?=$this->url(array('module'=>'auth', 'controller'=>'register','action'=>'index'));?>">Register</a>
            <? endif; ?>
<? $this->placeholder('body_start')->captureEnd(); ?>
