<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headTitle('Framework') ?> 
        <?= $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js') ?>
        <?= $this->headLink() ?>
        <?= $this->headMeta() ?>
    </head>
    <body>
        <?= $this->placeholder('body_start') ?>
        <div id="pageWrap">
            <?= $this->layout()->content; ?>
        </div>
        <?= $this->placeholder('body_end') ?>
    </body>
</html>
